Upgrade CI (16 Aug 2023 13:56:38)

diff --git a/.github/workflows/dco_workflow_complete.yaml b/.github/workflows/dco_workflow_complete.yaml
--- a/.github/workflows/dco_workflow_complete.yaml
+++ b/.github/workflows/dco_workflow_complete.yaml
@@ -38,7 +38,8 @@ jobs:
       - name: 'PR Number'
         id: pr-number
         run: |
-          PR=$(cat ./NR)
+          PR=$(tr -dc [0-9] <./NR)
+          [ -z "$PR" ] && echo "Invalid PR number" && exit 1
           echo "pr=${PR}" >> $GITHUB_OUTPUT
 
       - uses: actions/github-script@v6
@@ -65,11 +66,13 @@ jobs:
         if: needs.pr.outputs.pr != '0'
         uses: actions/github-script@v6
         continue-on-error: true
+        env:
+          PR: "${{ needs.pr.outputs.pr }}"
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
             github.rest.issues.removeLabel({
-              issue_number: ${{ needs.pr.outputs.pr }},
+              issue_number: process.env.PR,
               owner: context.repo.owner,
               repo: context.repo.repo,
               name: 'dco-failed'
