Upgrade CI (20 Feb 2023 14:39:05)

diff --git a/.github/workflows/operator_ci.yaml b/.github/workflows/operator_ci.yaml
--- a/.github/workflows/operator_ci.yaml
+++ b/.github/workflows/operator_ci.yaml
@@ -29,25 +29,25 @@ jobs:
     steps:
       - name: Remove automerge-disabled when needed
         if: ${{ env.AUTOMERGE_ENABLED == '1' }}
-        uses: actions/github-script@v3
+        uses: actions/github-script@v6
         continue-on-error: true
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
-            github.issues.removeLabel({
+            github.rest.issues.removeLabel({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
               name: 'automerge-disabled'
             })
       - name: Add automerge-disabled when needed
-        uses: actions/github-script@v3
+        uses: actions/github-script@v6
         if: ${{ env.AUTOMERGE_ENABLED == '0' }}
         continue-on-error: true
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
-            github.issues.addLabels({
+            github.rest.issues.addLabels({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
@@ -65,13 +65,13 @@ jobs:
       #     repo-token: "${{ secrets.GITHUB_TOKEN }}"
 
       - name: "Remove package-validated"
-        uses: actions/github-script@v3
+        uses: actions/github-script@v6
         if: (!contains(github.event.pull_request.labels.*.name, 'do-not-merge/hold'))
         continue-on-error: true
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
-            github.issues.removeLabel({
+            github.rest.issues.removeLabel({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
@@ -79,13 +79,13 @@ jobs:
             })
 
       - name: "Add Assignees"
-        uses: actions/github-script@v3
+        uses: actions/github-script@v6
         if: github.event.action == 'opened' || github.event.action == 'reopened'
         continue-on-error: true
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
-            github.issues.addAssignees({
+            github.rest.issues.addAssignees({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
@@ -113,7 +113,7 @@ jobs:
           bash <(curl -sL $OPP_SCRIPT_ENV_OPRT_URL)
 
       - name: "Remove installation-validated"
-        uses: actions/github-script@v4
+        uses: actions/github-script@v6
         if: (github.event.action != 'unlabeled')
         continue-on-error: true
         with:
@@ -122,7 +122,7 @@ jobs:
             const arr = ['installation-validated', 'installation-validated-atest', ];
 
             for (let label of arr) {
-              github.issues.removeLabel({
+              github.rest.issues.removeLabel({
                 issue_number: context.issue.number,
                 owner: context.repo.owner,
                 repo: context.repo.repo,
@@ -263,13 +263,13 @@ jobs:
           allow-repeats: true
 
       - name: Update title
-        uses: actions/github-script@v3
+        uses: actions/github-script@v6
         continue-on-error: true
         if: always() && steps.op-traffic-light.outputs.opp_pr_title != ''
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
-            github.issues.update({
+            github.rest.issues.update({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
@@ -277,13 +277,13 @@ jobs:
             })
 
       - name: Handle new operator
-        uses: actions/github-script@v3
+        uses: actions/github-script@v6
         if: steps.op-traffic-light.outputs.opp_is_new_operatror == '1'
         continue-on-error: true
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
-            github.issues.addLabels({
+            github.rest.issues.addLabels({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
@@ -297,11 +297,11 @@ jobs:
           OPP_MODIFIED_CSVS: "${{ steps.op-traffic-light.outputs.opp_modified_csvs }}"
           OPP_MODIFIED_CSVS_OTHERS: "${{ steps.op-traffic-light.outputs.opp_modified_others }}"
         run: |
-          echo "::set-output name=opp_check_cosmetic::0"
+          echo "opp_check_cosmetic=0" >> $GITHUB_OUTPUT
           [[ $OPP_RECREATE -eq 1 ]] && { echo "Recreating operator. Exiting with '0' ..."; exit 0; } || true
           [[ $OPP_ALLOW_SERIOUS_CHANGES -eq 1 ]] && { echo "Allowing serious changes. Exiting with '0' ..."; exit 0; } || true
-          [ -n "$OPP_MODIFIED_CSVS" ] && echo "::set-output name=opp_check_cosmetic::1" || true
-          [ -n "$OPP_MODIFIED_CSVS_OTHERS" ] && { echo -e "Error:\n    Modifying exiting operator version !!!\n    Only cosmetic changes are allowed !!! Please ask maintainers to set 'allow/serious-changes-to-existing' label.\n    Files that cannot be changed : '$OPP_MODIFIED_CSVS_OTHERS'"; echo "::set-output name=opp_check_cosmetic::2"; exit 20; } || true
+          [ -n "$OPP_MODIFIED_CSVS" ] && echo "opp_check_cosmetic=1" >> $GITHUB_OUTPUT || true
+          [ -n "$OPP_MODIFIED_CSVS_OTHERS" ] && { echo -e "Error:\n    Modifying exiting operator version !!!\n    Only cosmetic changes are allowed !!! Please ask maintainers to set 'allow/serious-changes-to-existing' label.\n    Files that cannot be changed : '$OPP_MODIFIED_CSVS_OTHERS'"; echo "opp_check_cosmetic=2" >> $GITHUB_OUTPUT; exit 20; } || true
 
       - name: "Comment for cosmetics change error when csv is changed"
         if: failure() && steps.op-verify-modifications.outputs.opp_check_cosmetic == '2'
@@ -352,48 +352,48 @@ jobs:
           allow-repeats: true
 
       - name: "Removing Operator recreate label when exists"
-        uses: actions/github-script@v3
+        uses: actions/github-script@v6
         if: steps.op-traffic-light.outputs.opp_set_label_operator_version_overwrite == '1' && contains(github.event.pull_request.labels.*.name, 'allow/operator-recreate')
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
-            github.issues.removeLabel({
+            github.rest.issues.removeLabel({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
               name: 'allow/operator-recreate'
             })
       - name: "Setting Operator version overwrite label"
-        uses: actions/github-script@v3
+        uses: actions/github-script@v6
         if: steps.op-traffic-light.outputs.opp_set_label_operator_version_overwrite == '1'
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
-            github.issues.addLabels({
+            github.rest.issues.addLabels({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
               labels: [ 'allow/operator-version-overwrite' ]
             })
       - name: "Removing Operator version overwrite label when exists"
-        uses: actions/github-script@v3
+        uses: actions/github-script@v6
         if: steps.op-traffic-light.outputs.opp_set_label_operator_recreate == '1' && contains(github.event.pull_request.labels.*.name, 'allow/operator-version-overwrite')
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
-            github.issues.removeLabel({
+            github.rest.issues.removeLabel({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
               name: 'allow/operator-version-overwrite'
             })
       - name: "Setting Operator recreate label"
-        uses: actions/github-script@v3
+        uses: actions/github-script@v6
         if: steps.op-traffic-light.outputs.opp_set_label_operator_recreate == '1'
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
-            github.issues.addLabels({
+            github.rest.issues.addLabels({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
@@ -417,12 +417,12 @@ jobs:
       #     configuration-path: "${{steps.op-traffic-light.outputs.opp_production_type }}/${{ steps.op-traffic-light.outputs.opp_name }}/ci.yaml"
 
       - name: "Setting authorized-changes label"
-        uses: actions/github-script@v3
+        uses: actions/github-script@v6
         if: steps.op-traffic-light.outputs.opp_authorized_changes == '1'
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
-            github.issues.addLabels({
+            github.rest.issues.addLabels({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
@@ -469,13 +469,13 @@ jobs:
     steps:
 
       - name: "Remove needs-ok-to-test"
-        uses: actions/github-script@v3
+        uses: actions/github-script@v6
         if: always()
         continue-on-error: true
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
-            github.issues.removeLabel({
+            github.rest.issues.removeLabel({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
@@ -488,12 +488,12 @@ jobs:
           echo "needs.operator-ci.outputs.opp_installation_skipped: ${{ needs.operator-ci.outputs.opp_installation_skipped }}"
 
       - name: "Setting ok-to-test label"
-        uses: actions/github-script@v3
+        uses: actions/github-script@v6
         if: needs.operator-ci.outputs.opp_production_type != 'k8s' && needs.operator-ci.outputs.opp_ci_yaml_only != '1' && (!contains(github.event.pull_request.labels.*.name, 'allow/ci-changes')) && needs.operator-ci.outputs.opp_installation_skipped == '0'
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
-            github.issues.addLabels({
+            github.rest.issues.addLabels({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
@@ -501,12 +501,12 @@ jobs:
             })
 
       - name: "Setting installation-validated label (opensift+ci_yaml_only)"
-        uses: actions/github-script@v3
+        uses: actions/github-script@v6
         if: needs.operator-ci.outputs.opp_production_type != 'k8s' && needs.operator-ci.outputs.opp_ci_yaml_only == '1'
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
-            github.issues.addLabels({
+            github.rest.issues.addLabels({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
@@ -514,13 +514,13 @@ jobs:
             })
 
       - name: "Setting installation-validated label (when installation_skipped)"
-        uses: actions/github-script@v3
+        uses: actions/github-script@v6
         if: needs.operator-ci.outputs.opp_installation_skipped == '1'
         continue-on-error: true
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
-            github.issues.addLabels({
+            github.rest.issues.addLabels({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
@@ -528,13 +528,13 @@ jobs:
             })
 
       - name: Try to automerge
-        uses: actions/github-script@v3
+        uses: actions/github-script@v6
         if: needs.operator-ci.outputs.opp_production_type != 'k8s' && needs.operator-ci.outputs.opp_ci_yaml_only == '1'
         continue-on-error: true
         with:
           github-token: ${{ secrets.FRAMEWORK_MERGE }}
           script: |
-            github.issues.createComment({
+            github.rest.issues.createComment({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
